<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <nav class="navbar navbar-inverse">
       <div class="container-fluid">
           <div class="navbar-header">
                <a id="logo" class="navbar-brand" href=<?= $linkTo('Welcome'); ?>></a>
            </div>
           <ul class="nav navbar-nav">
               <li class="active"><a href="#">Browse</a></li>
               <li><a href=<?= $linkTo('Search'); ?>>Search</a></li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
              <li><a href="/../ToolshedInc/login" name="logout" class="btn" role="button"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
           </ul>
       </div>
    </nav>

<div class="">
    <h3 id="browse">Browse Products:</h3>
    <div id="browse-check-boxes" class="col-sm-4">
        <form action="">
            <div>
                <label>In stock only</label>
                <input type="checkbox" id="inStock" onclick="reloadTable()">
            </div>
            <br>
            <div>
                <label>Hammers</label>
                <input type="checkbox" id="hammers" onclick="reloadTable()">
            </div>
            <div>
                <label>Heat Guns</label>
                <input type="checkbox" id="heat-guns" onclick="reloadTable()">
            </div>
            <div>
                <label>Pliers</label>
                <input type="checkbox" id="pliers" onclick="reloadTable()">
            </div>
            <div>
                <label>Screwdrivers</label>
                <input type="checkbox" id="screwdrivers" onclick="reloadTable()">
            </div>
            <div>
                <label>Spanners and Wrenches</label>
                <input type="checkbox" id="spanners" onclick="reloadTable()">
            </div>
        </form>
    </div>

    <table id="browse-table" class="table table-striped">
        <thead>
        <tr>
            <th>SKU</th>
            <th>Product Name</th>
            <th>Cost</th>
            <th>Stock Quantity</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<!---------- Body ends -------------------->

<script>
//this function runs every time the user checks a checkbox
//to update the table with the new criteria
function reloadTable(){
    var stock = document.getElementById("inStock").checked;
    var ham = document.getElementById("hammers").checked;
    var heat = document.getElementById("heat-guns").checked;
    var pliers = document.getElementById("pliers").checked;
    var screw = document.getElementById("screwdrivers").checked;
    var span = document.getElementById("spanners").checked;
    $.post("/browsing",
    {
      stock: stock,
      hammer: ham,
      heat: heat,
      pliers: pliers,
      screw: screw,
      span: span
    },
    function(data){
        var res = data.split("|");
        var table = document.getElementById('browse-table').getElementsByTagName('tbody')[0];
        table.innerHTML = ""; //wiping results every time so duplicate rows are not added
        for(var i = 0; i < res.length-1; i++) {
            var row = table.insertRow(table.rows.length);
            var cell1 = row.insertCell(0);
            var cell2 = row.insertCell(1);
            var cell3 = row.insertCell(2);
            var cell4 = row.insertCell(3);

            //inserting cells into table
            var res2 = res[i].split(":");
            cell1.innerHTML = res2[0];
            cell2.innerHTML = res2[1];
            cell3.innerHTML = "$" + res2[2];
            cell4.innerHTML = res2[3];
        }
    })
}

</script>

<?php include "footer.phtml" ?>