<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a id="logo" class="navbar-brand" href=<?= $linkTo('Login'); ?>></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href=<?= $linkTo('Register'); ?>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href=<?= $linkTo('Login'); ?>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </nav>

    <div>
        <h3> <?= $data?> </h3>
    </div>

    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>