<?php include "header.phtml" ?>
    <!---------- Body starts --------------->

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a id="logo" class="navbar-brand" href=<?= $linkTo('Login'); ?>></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href=<?= $linkTo('Register'); ?>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <form action="../../Toolshedinc/login/welcome/" method="post">
            <div class="form-group">
                <label class="col-sm-2">Username:</label>
                <div class="notInline col-sm-4">
                    <input type="text" class="form-control" placeholder="Enter username" name="userName" required="required">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2">Password:</label>
                <div class="notInline col-sm-4">
                    <input type="password" class="form-control" placeholder="Enter password" name="password" required="required">
                </div>
            </div>
            <div class="col-sm-4">
                <button name="Welcome" type="submit" class="btn btn-default">Log in</button>
            </div>
        </form>
    </div>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>